[features]
seeds = false
skip-lint = false
[programs.devnet]
vetra = "74HrdaZXYxhozpW85ZicG1pJm4Fkf6PrxdPENeHXsXgK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/vingitonga/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
